package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/t-yuki/zipkin-go/client/operations"
)

// Default zipkin HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new zipkin HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Zipkin {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost:9411", "/", []string{"http", "https"})
	return New(transport, formats)
}

// New creates a new zipkin client
func New(transport client.Transport, formats strfmt.Registry) *Zipkin {
	cli := new(Zipkin)
	cli.Transport = transport

	cli.Operations = operations.New(transport, formats)

	return cli
}

// Zipkin is a client for zipkin
type Zipkin struct {
	Operations *operations.Client

	Transport client.Transport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Zipkin) SetTransport(transport client.Transport) {
	c.Transport = transport

	c.Operations.SetTransport(transport)

}
