package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/t-yuki/zipkin-go/models"
)

/*GetTraceTraceIDOK OK

swagger:response getTraceTraceIdOK
*/
type GetTraceTraceIDOK struct {

	// In: body
	Payload []models.Trace `json:"body,omitempty"`
}

// NewGetTraceTraceIDOK creates GetTraceTraceIDOK with default headers values
func NewGetTraceTraceIDOK() *GetTraceTraceIDOK {
	return &GetTraceTraceIDOK{}
}

// WithPayload adds the payload to the get trace trace id o k response
func (o *GetTraceTraceIDOK) WithPayload(payload []models.Trace) *GetTraceTraceIDOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *GetTraceTraceIDOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetTraceTraceIDNotFound `traceId` not found

swagger:response getTraceTraceIdNotFound
*/
type GetTraceTraceIDNotFound struct {
}

// NewGetTraceTraceIDNotFound creates GetTraceTraceIDNotFound with default headers values
func NewGetTraceTraceIDNotFound() *GetTraceTraceIDNotFound {
	return &GetTraceTraceIDNotFound{}
}

// WriteResponse to the client
func (o *GetTraceTraceIDNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
}
