package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/t-yuki/zipkin-go/models"
)

/*GetDependenciesOK OK

swagger:response getDependenciesOK
*/
type GetDependenciesOK struct {

	// In: body
	Payload []*models.DependencyLink `json:"body,omitempty"`
}

// NewGetDependenciesOK creates GetDependenciesOK with default headers values
func NewGetDependenciesOK() *GetDependenciesOK {
	return &GetDependenciesOK{}
}

// WithPayload adds the payload to the get dependencies o k response
func (o *GetDependenciesOK) WithPayload(payload []*models.DependencyLink) *GetDependenciesOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *GetDependenciesOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
