package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/t-yuki/zipkin-go/models"
)

/*GetTracesOK OK

swagger:response getTracesOK
*/
type GetTracesOK struct {

	// In: body
	Payload models.ListOfTraces `json:"body,omitempty"`
}

// NewGetTracesOK creates GetTracesOK with default headers values
func NewGetTracesOK() *GetTracesOK {
	return &GetTracesOK{}
}

// WithPayload adds the payload to the get traces o k response
func (o *GetTracesOK) WithPayload(payload models.ListOfTraces) *GetTracesOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *GetTracesOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
