package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// GetServicesHandlerFunc turns a function with the right signature into a get services handler
type GetServicesHandlerFunc func() middleware.Responder

// Handle executing the request and returning a response
func (fn GetServicesHandlerFunc) Handle() middleware.Responder {
	return fn()
}

// GetServicesHandler interface for that can handle valid get services params
type GetServicesHandler interface {
	Handle() middleware.Responder
}

// NewGetServices creates a new http.Handler for the get services operation
func NewGetServices(ctx *middleware.Context, handler GetServicesHandler) *GetServices {
	return &GetServices{Context: ctx, Handler: handler}
}

/*GetServices swagger:route GET /services getServices

Returns a list of all service names associated with annotations.


*/
type GetServices struct {
	Context *middleware.Context
	Handler GetServicesHandler
}

func (o *GetServices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle() // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
