package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*GetSpansOK OK

swagger:response getSpansOK
*/
type GetSpansOK struct {

	// In: body
	Payload []string `json:"body,omitempty"`
}

// NewGetSpansOK creates GetSpansOK with default headers values
func NewGetSpansOK() *GetSpansOK {
	return &GetSpansOK{}
}

// WithPayload adds the payload to the get spans o k response
func (o *GetSpansOK) WithPayload(payload []string) *GetSpansOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *GetSpansOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetSpansBadRequest Bad Request Error

swagger:response getSpansBadRequest
*/
type GetSpansBadRequest struct {
}

// NewGetSpansBadRequest creates GetSpansBadRequest with default headers values
func NewGetSpansBadRequest() *GetSpansBadRequest {
	return &GetSpansBadRequest{}
}

// WriteResponse to the client
func (o *GetSpansBadRequest) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(400)
}
