package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// PostSpansHandlerFunc turns a function with the right signature into a post spans handler
type PostSpansHandlerFunc func(PostSpansParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSpansHandlerFunc) Handle(params PostSpansParams) middleware.Responder {
	return fn(params)
}

// PostSpansHandler interface for that can handle valid post spans params
type PostSpansHandler interface {
	Handle(PostSpansParams) middleware.Responder
}

// NewPostSpans creates a new http.Handler for the post spans operation
func NewPostSpans(ctx *middleware.Context, handler PostSpansHandler) *PostSpans {
	return &PostSpans{Context: ctx, Handler: handler}
}

/*PostSpans swagger:route POST /spans postSpans

Uploads a list of spans encoded per content-type

*/
type PostSpans struct {
	Context *middleware.Context
	Params  PostSpansParams
	Handler PostSpansHandler
}

func (o *PostSpans) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	o.Params = NewPostSpansParams()

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(o.Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
