package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*PostSpansAccepted Created

swagger:response postSpansAccepted
*/
type PostSpansAccepted struct {
}

// NewPostSpansAccepted creates PostSpansAccepted with default headers values
func NewPostSpansAccepted() *PostSpansAccepted {
	return &PostSpansAccepted{}
}

// WriteResponse to the client
func (o *PostSpansAccepted) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(202)
}
