package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/go-swagger/go-swagger/spec"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewZipkinAPI creates a new Zipkin instance
func NewZipkinAPI(spec *spec.Document) *ZipkinAPI {
	o := &ZipkinAPI{
		spec:            spec,
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/x-thrift",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
	}

	return o
}

/*ZipkinAPI Zipkin's Query api is rooted at `api/v1`, on a host that by default listens
on port 9411. It primarily serves zipkin-web, although it includes a POST
endpoint that can receive spans.
*/
type ZipkinAPI struct {
	spec            *spec.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	// ThriftConsumer registers a consumer for a "application/x-thrift" mime type
	ThriftConsumer httpkit.Consumer
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer httpkit.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer httpkit.Producer

	// GetDependenciesHandler sets the operation handler for the get dependencies operation
	GetDependenciesHandler GetDependenciesHandler
	// GetServicesHandler sets the operation handler for the get services operation
	GetServicesHandler GetServicesHandler
	// GetSpansHandler sets the operation handler for the get spans operation
	GetSpansHandler GetSpansHandler
	// GetTraceTraceIDHandler sets the operation handler for the get trace trace ID operation
	GetTraceTraceIDHandler GetTraceTraceIDHandler
	// GetTracesHandler sets the operation handler for the get traces operation
	GetTracesHandler GetTracesHandler
	// PostSpansHandler sets the operation handler for the post spans operation
	PostSpansHandler PostSpansHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup
}

// SetDefaultProduces sets the default produces media type
func (o *ZipkinAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *ZipkinAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// DefaultProduces returns the default produces media type
func (o *ZipkinAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *ZipkinAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *ZipkinAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *ZipkinAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the ZipkinAPI
func (o *ZipkinAPI) Validate() error {
	var unregistered []string

	if o.ThriftConsumer == nil {
		unregistered = append(unregistered, "ThriftConsumer")
	}

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.GetDependenciesHandler == nil {
		unregistered = append(unregistered, "GetDependenciesHandler")
	}

	if o.GetServicesHandler == nil {
		unregistered = append(unregistered, "GetServicesHandler")
	}

	if o.GetSpansHandler == nil {
		unregistered = append(unregistered, "GetSpansHandler")
	}

	if o.GetTraceTraceIDHandler == nil {
		unregistered = append(unregistered, "GetTraceTraceIDHandler")
	}

	if o.GetTracesHandler == nil {
		unregistered = append(unregistered, "GetTracesHandler")
	}

	if o.PostSpansHandler == nil {
		unregistered = append(unregistered, "PostSpansHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *ZipkinAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *ZipkinAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]httpkit.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *ZipkinAPI) ConsumersFor(mediaTypes []string) map[string]httpkit.Consumer {

	result := make(map[string]httpkit.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/x-thrift":
			result["application/x-thrift"] = o.ThriftConsumer

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *ZipkinAPI) ProducersFor(mediaTypes []string) map[string]httpkit.Producer {

	result := make(map[string]httpkit.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *ZipkinAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

func (o *ZipkinAPI) initHandlerCache() {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/dependencies"] = NewGetDependencies(o.context, o.GetDependenciesHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/services"] = NewGetServices(o.context, o.GetServicesHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/spans"] = NewGetSpans(o.context, o.GetSpansHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/trace/{traceId}"] = NewGetTraceTraceID(o.context, o.GetTraceTraceIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/traces"] = NewGetTraces(o.context, o.GetTracesHandler)

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/spans"] = NewPostSpans(o.context, o.PostSpansHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *ZipkinAPI) Serve(builder middleware.Builder) http.Handler {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}

	return o.context.APIHandler(builder)
}
