package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/t-yuki/zipkin-go/models"
)

// GetTracesReader is a Reader for the GetTraces structure.
type GetTracesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetTracesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTracesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTracesOK creates a GetTracesOK with default headers values
func NewGetTracesOK() *GetTracesOK {
	return &GetTracesOK{}
}

/*GetTracesOK handles this case with default header values.

OK
*/
type GetTracesOK struct {
	Payload models.ListOfTraces
}

func (o *GetTracesOK) Error() string {
	return fmt.Sprintf("[GET /traces][%d] getTracesOK  %+v", 200, o.Payload)
}

func (o *GetTracesOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
