package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/t-yuki/zipkin-go/models"
)

// NewPostSpansParams creates a new PostSpansParams object
// with the default values initialized.
func NewPostSpansParams() *PostSpansParams {
	var ()
	return &PostSpansParams{}
}

/*PostSpansParams contains all the parameters to send to the API endpoint
for the post spans operation typically these are written to a http.Request
*/
type PostSpansParams struct {

	/*Span
	  A list of spans

	*/
	Span models.ListOfSpans
}

// WithSpan adds the span to the post spans params
func (o *PostSpansParams) WithSpan(span models.ListOfSpans) *PostSpansParams {
	o.Span = span
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostSpansParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	valuesSpan := o.Span
	joinedSpan := swag.JoinByFormat(valuesSpan, "")

	if err := r.SetBodyParam(o.Span); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
