package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*BinaryAnnotation BinaryAnnotation

swagger:model BinaryAnnotation
*/
type BinaryAnnotation struct {

	/* Endpoint endpoint
	 */
	Endpoint *Endpoint `json:"endpoint,omitempty"`

	/* Key key
	 */
	Key *string `json:"key,omitempty"`

	/* Value value
	 */
	Value *string `json:"value,omitempty"`
}

// Validate validates this binary annotation
func (m *BinaryAnnotation) Validate(formats strfmt.Registry) error {
	return nil
}
