package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Endpoint Endpoint

swagger:model Endpoint
*/
type Endpoint struct {

	/* IPV4 ipv4
	 */
	IPV4 *string `json:"ipv4,omitempty"`

	/* Port port
	 */
	Port *int64 `json:"port,omitempty"`

	/* ServiceName service name
	 */
	ServiceName *string `json:"serviceName,omitempty"`
}

// Validate validates this endpoint
func (m *Endpoint) Validate(formats strfmt.Registry) error {
	return nil
}
